#!/usr/bin/env python
# -*- coding: UTF-8 -*-


def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('raise_example')

def _configure():
	os.environ['CC'] = 'gcc'
	os.environ['CFLAGS'] = '-g -Wall -Werror'

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the program
	c_build_program('raise_example', ['main.c'])

	# Run the program
	run_say('./raise_example')

def _remove():
	rmfile_f('/usr/bin/raise_example')

def remove():
	"""Uninstalls the program."""
	# Setup
	require_root()
	clean()

	# Remove the old files
	_remove()

	updatedb()

def install():
	"""Installs the program."""
	# Setup
	require_root()
	clean()
	_configure()

	# Build as a normal user
	def actual_build():
		c_build_program('raise_example', ['main.c'])
	do_as_normal_user(actual_build)

	# Remove old install
	_remove()

	# Install
	cpfile('raise_example', '/usr/bin/raise_example')

	updatedb()



