#!/usr/bin/env python
# -*- coding: UTF-8 -*-


def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('raise_example')

def _configure():
	os.environ['CC'] = 'gcc'
	os.environ['CFLAGS'] = '-g -Wall -Werror'

def test():
	"""Builds the program, and runs it."""
	clean()
	_configure()

	c_build_program('raise_example', ['main.c'])

	run_say('./raise_example')

def remove():
	"""Uninstalls the program."""
	require_root()
	clean()

	rmfile_f('/usr/bin/raise_example')

def install():
	"""Installs the program."""
	require_root()
	clean()
	remove()

	_configure()
	c_build_program('raise_example', ['main.c'])

	cpfile('raise_example', '/usr/bin/raise_example')



