#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_c as C
import lib_raise_linker as Linker
import lib_raise_fs as FS
import lib_raise_find as Find
import lib_raise_users as Users
import lib_raise_process as Process

def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('raise_example')
	FS.remove_binaries('main')

def _configure():
	cc = C.get_default_compiler()
	cc.standard = C.Standard.std2011
	cc.debug = True
	cc.optimize_level = 2
	cc.warnings_all = True
	cc.warnings_as_errors = True
	return cc

def test():
	"""Builds the program, and runs it."""
	# Setup
	Users.require_not_root()
	clean()
	cc = _configure()

	# Build the program
	cc.build_program('raise_example.exe', ['main.c'])

	# Run the program
	C.run_print('./raise_example.exe')

def _remove():
	C.uninstall_program('raise_example.exe')

def remove():
	"""Uninstalls the program."""
	# Setup
	Users.require_root()
	clean()
	cc = _configure()

	# Remove the old files
	_remove()

def install():
	"""Installs the program."""
	# Setup
	Users.require_root()
	clean()
	cc = _configure()

	# Build as a normal user
	def actual_build():
		cc.build_program('raise_example.exe', ['main.c'])
	Users.do_as_normal_user(actual_build)

	# Remove old install
	_remove()

	# Install
	C.install_program('raise_example.exe')





