#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
from lib_raise_csharp import *

def clean():
	"""Removes any files and directories generated when building."""
	remove_binaries('lib_math')
	remove_binaries('main')

def _configure():
	csc = csharp_get_default_compiler()
	csc.debug = True
	csc.optimize = True
	csc.warnings_all = True
	csc.warnings_as_errors = True
	csharp_save_compiler(csc)

def setup_failure():
	# Empty the path and reset the CSharp module so it finds no compilers
	os.environ['PATH'] = ''
	CSharp.is_setup = False
	CSharp.cs_compilers = {}
	CSharp.cs_runtimes = {}
	CSharp.csc = None
	CSharp.runtime = None
	CSharp.call_setup()

def build_program():
	clean()
	_configure()

	csharp_build_program('main.exe', ['main.cs', 'lib_math.cs'])

	csharp_run_say('main.exe')

def build_shared_library():
	clean()
	_configure()

	csharp_build_shared_library('lib_math.dll', ['lib_math.cs'])
	csharp_build_program('main.exe', ['main.cs'], ['-r:lib_math.dll'])

	csharp_run_say('main.exe')

