#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_terminal as Print
import lib_raise_libraries as Libraries
import lib_raise_os as OS
import lib_raise_csharp as CSharp
import lib_raise_fs as FS

def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('lib_math')
	FS.remove_binaries('main')

def _configure():
	csc = CSharp.get_default_compiler()
	csc.debug = True
	csc.optimize = True
	csc.warnings_all = True
	csc.warnings_as_errors = True
	CSharp.save_compiler(csc)

def setup_failure():
	# Empty the path and reset the CSharp module so it finds no compilers
	os.environ['PATH'] = ''
	CSharp.is_setup = False
	CSharp.cs_compilers = {}
	CSharp.cs_runtimes = {}
	CSharp.csc = None
	CSharp.runtime = None
	CSharp.setup()

def build_program():
	clean()
	_configure()

	CSharp.build_program('main.exe', ['main.cs', 'lib_math.cs'])

	CSharp.run_say('main.exe')

def build_shared_library():
	clean()
	_configure()

	CSharp.build_shared_library('lib_math.dll', ['lib_math.cs'])
	CSharp.build_program('main.exe', ['main.cs'], ['-r:lib_math.dll'])

	CSharp.run_say('main.exe')

