#!/usr/bin/env python
# -*- coding: UTF-8 -*-

'''
This file is part of Raise a small build automation tool.
This project is hosted at http://launchpad.net/raise .

Copyright (c) 2012, Matthew Brennan Jones<mattjones@workhorsy.org>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met: 

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer. 
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies, 
either expressed or implied, of the FreeBSD Project.
'''

import os, sys
import stat
if sys.version_info < (3, 0):
	import urllib2
	globals()['urlopen'] = urllib2.urlopen
else:
	import urllib.request
	globals()['urlopen'] = urllib.request.urlopen

def friendly_size(data_length):
	retval = ''
	size_map = [
		{'B'  : 1},
		{'KB' : 1024.0},
		{'MB' : 1024000.0},
		{'GB' : 1024000000.0}
	]
	for i in size_map:
		for name, size in i.items():
			if data_length >= size:
				retval = '{0} {1}'.format(round(data_length / size, 2), name)
				break

	return retval

def download_file(url, cb):
	chunk_size = 1024
	response = urlopen(url)
	content_length = int(response.headers['Content-Length'])
	data = b''
	data_length = 0

	while True:
		chunk = response.read(chunk_size)
		if not chunk:
			break

		data += chunk
		data_length += len(chunk)
		percent = round((float(data_length) / content_length)*100, 2)

		cb(chunk, data_length, chunk_size, content_length, percent)

def update():
	print("Downloading newest Raise version ...")
	try:
		url = 'http://bazaar.launchpad.net/~workhorsy/raise/main/download/head:/raise-20120417054845-dmqxla979coc2eqq-1/raise_actual'
		f = open('.raise_actual', 'wb')

		def cb(chunk, data_length, chunk_size, content_length, percent):
			# Write the next chunk to the file
			f.write(chunk)

			# Write the download progress
			sys.stdout.write("Downloaded {0} of {1} ({2}%)\r".format(friendly_size(data_length), friendly_size(content_length), percent))

			# Write a newline if the download is complete
			if data_length >= content_length:
				sys.stdout.write('\n')

			sys.stdout.flush()

		# Download the file and call the cb after each chunk
		download_file(url, cb)

		# Make the file executable
		os.chmod('.raise_actual', 0775 | stat.S_IXOTH)
	except Exception as e:
		print(str(e))

if __name__ == '__main__':
	# Clear the terminal if ran as clear; ./raise
	os.system('clear')

	args = str(str.join(' ', sys.argv[1:]))
	if args == 'update':
		update()
		exit()

	if not os.path.isfile('.raise_actual'):
		update()

	os.system('./.raise_actual ' + args)


