#!/usr/bin/env python
# -*- coding: UTF-8 -*-


RAISE_VERSION = '0.1'
RAISE_PATH = '/usr/bin/raise'


def clean():
	pass

def configure():
	os.environ["RAISE_VERSION"] = RAISE_VERSION
	os.environ["RAISE_PATH"] = RAISE_PATH

def remove():
	require_root()
	clean()

	rmfile_f(RAISE_PATH)

def install():
	require_root()
	clean()
	remove()
	configure()

	# Copy the files to the system directory
	cpfile('raise', RAISE_PATH)

def test():
	print('See examples in /examples directory.')

