#!/usr/bin/env python
# -*- coding: UTF-8 -*-


def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('raise_example')
	rmfile_f('libexample.o')
	rmfile_f('libexample.so')

def _configure():
	os.environ['CC'] = 'gcc'
	os.environ['CFLAGS'] = '-g -Wall -Werror'
	os.environ['LD_LIBRARY_PATH'] = os.getcwd()

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the library
	c_build_object('libexample.o', ['libexample.c'])
	c_build_shared_library('libexample.so', ['libexample.o'])

	# Build the program and link against the library
	c_build_program('raise_example', ['main.c'], ['${LD_LIBRARY_PATH}/libexample.so'])

	# Run the program
	run_say('./raise_example')

def _remove():
	rmfile_f('/usr/bin/raise_example')
	rmfile_f('/usr/lib/libexample.so')

def remove():
	"""Uninstalls the program."""
	# Setup
	require_root()
	clean()

	# Remove the old files
	_remove()

	updatedb()
	ldconfig()

def install():
	"""Installs the program."""
	# Setup
	require_root()
	clean()
	_configure()

	# Build as a normal user
	def actual_build():
		c_build_object('libexample.o', ['libexample.c'])
		c_build_shared_library('libexample.so', ['libexample.o'])
		c_build_program('raise_example', ['main.c'], ['libexample.so'])
	do_as_normal_user(actual_build)

	# Remove old install
	_remove()

	# Install
	cpfile('raise_example', '/usr/bin/raise_example')
	cpfile('libexample.so', '/usr/lib/libexample.so')

	updatedb()
	ldconfig()





