#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_terminal as Print
import lib_raise_libraries as Libraries
import lib_raise_os as OS
import lib_raise_c as C
import lib_raise_linker as Linker
import lib_raise_ar as AR
import lib_raise_fs as FS


def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('lib_math')
	FS.remove_binaries('main')

def _configure():
	cc = C.get_default_compiler()
	cc.debug = True
	cc.optimize = True
	cc.warnings_all = True
	cc.warnings_as_errors = True
	C.save_compiler(cc)

	linker = Linker.get_default_linker()
	Linker.save_linker(linker)

	os.environ['LD_LIBRARY_PATH'] = os.getcwd()

def setup_failure():
	# Empty the path and reset the C module so it finds no compilers
	os.environ['PATH'] = ''
	C.is_setup = False
	C.c_compilers = {}
	C.cc = None
	C.setup()

def build_object():
	clean()
	_configure()

	C.build_object('lib_math.o', ['lib_math.c'])
	C.build_object('main.o', ['main.c'])

	C.build_program('main.exe', ['lib_math.o', 'main.o'])

	C.run_say('./main.exe')

def build_program():
	clean()
	_configure()

	C.build_program('main.exe', ['lib_math.c', 'main.c'])

	C.run_say('./main.exe')

def build_shared_library():
	clean()
	_configure()

	# Build the library
	C.build_object('lib_math.o', ['lib_math.c'])
	C.build_shared_library('lib_math.so', ['lib_math.o'])

	C.build_program('main.exe', ['main.c', 'lib_math.so'])

	C.run_say('./main.exe')

def build_static_library():
	clean()
	_configure()

	# Build the library
	C.build_object('lib_math.o', ['lib_math.c'])
	AR.build_static_library('lib_math.a', ['lib_math.o'])

	C.build_program('main.exe', ['main.c', 'lib_math.a'])

	C.run_say('./main.exe')

