#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import_module('C')


def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('lib_math.o')
	rmfile_f('main.o')
	rmfile_f('main')

def _configure():
	cc = c_get_default_compiler()
	cc.debug = True
	cc.optimize = True
	cc.warnings_all = True
	cc.warnings_as_errors = True
	c_save_compiler(cc)

def build_object():
	clean()
	_configure()

	c_build_object('lib_math.o', ['lib_math.c'])
	c_build_object('main.o', ['main.c'])

	c_build_program('main', ['lib_math.o', 'main.o'])

	run_say('./main')

def build_program():
	clean()
	_configure()

	c_build_program('main', ['lib_math.c', 'main.c'])

	run_say('./main')



