#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_cxx as CXX
import lib_raise_linker as Linker
import lib_raise_ar as AR
import lib_raise_fs as FS
import lib_raise_find as Find
import lib_raise_users as Users
import lib_raise_process as Process

def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('raise_example')
	FS.remove_binaries('main')

def _configure():
	cxx = CXX.get_default_compiler()
	cxx.standard = CXX.Standard.std2011
	cxx.debug = True
	cxx.optimize_level = 2
	cxx.warnings_all = False
	cxx.warnings_as_errors = True
	cxx.compile_time_flags = ['ADD', 'MULTIPLY']
	return cxx

def test():
	"""Builds the program, and runs it."""
	# Setup
	Users.require_not_root()
	clean()
	cxx = _configure()

	# Build the program
	cxx.build_program('raise_example.exe', ['main.cc'])

	# Run the program
	CXX.run_print('./raise_example.exe')





