#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from lib_raise_cxx import *

def clean():
	"""Removes any files and directories generated when building."""
	rm_binaries('raise_example')
	rm_binaries('main')

def _configure():
	cxx = cxx_get_default_compiler()
	cxx.debug = True
	cxx.optimize = True
	cxx.warnings_all = True
	cxx.warnings_as_errors = True
	cxx.compile_time_flags = ['ADD', 'MULTIPLY']
	cxx_save_compiler(cxx)

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the program
	cxx_build_program('raise_example.exe', ['main.cc'])

	# Run the program
	cxx_run_say('./raise_example.exe')





