#!/usr/bin/env python
# -*- coding: UTF-8 -*-


def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('a.out')
	rmfile_f('raise_example.o')
	rmfile_f('raise_example')
	rmfile_f('lib_regex.o')

def _configure():
	require_programs(['dmd'])

	os.environ['CC'] = 'gcc'
	os.environ['DC'] = 'dmd'
	os.environ['CFLAGS'] = '-g -Wall -Werror'
	os.environ['DFLAGS'] = '-g -w'

	require_shared_libraries(['libpcre'])
	require_static_libraries(['libphobos2'])

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the C object file
	c_build_object('lib_regex.o', ['lib_regex.c'])

	# Build the D program using the C object file
	d_build_program('raise_example', ['main.d', 'lib_regex.o', 'lib_regex.d'], ['-L-lpcre'])

	# Run the program
	run_say('./raise_example')

def _remove():
	rmfile_f('/usr/bin/raise_example')
	rmfile_f('/usr/lib/lib_regex.so')

def remove():
	"""Uninstalls the program."""
	# Setup
	require_root()
	clean()

	# Remove the files
	_remove()

	updatedb()
	ldconfig()

def install():
	"""Installs the program."""
	# Setup
	require_root()
	clean()
	_configure()

	# Build as a normal user
	def actual_build():
		c_build_object('lib_regex.o', ['lib_regex.c'])
		c_build_shared_library('lib_regex.so', ['lib_regex.o'])
		d_build_program('raise_example', ['main.d', 'lib_regex.d'], ['-Llib_regex.so', '-L-lpcre'])
	do_as_normal_user(actual_build)

	# Remove old install
	_remove()

	# Install
	cpfile('raise_example', '/usr/bin/raise_example')
	cpfile('lib_regex.so', '/usr/lib/lib_regex.so')

	updatedb()
	ldconfig()


