#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import lib_raise_terminal as Print
import lib_raise_find as Find
import lib_raise_os as OS

def simple_nothing():
	pass

def simple_status():
	Print.status('Simple status')

def simple_ok():
	Print.status('Simple ok')
	Print.ok()

def simple_fail():
	Print.status('Simple fail')
	Print.fail()

def simple_warning():
	Print.status('Simple warning')
	Print.warning()

def simple_require_program():
	Find.require_programs(['python'])

def simple_require_program_failure():
	Find.require_programs(['no_such_program'])

def simple_require_not_root():
	OS.require_not_root()

def simple_require_root_failure():
	OS.require_root()

# Tests that require root
def simple_require_root():
	OS.require_root()

def simple_require_not_root_failure():
	OS.require_not_root()

