#!/usr/bin/env python
# -*- coding: UTF-8 -*-

def simple_nothing():
	pass

def simple_status():
	print_status('Simple status')

def simple_ok():
	print_status('Simple ok')
	print_ok()

def simple_fail():
	print_status('Simple fail')
	print_fail()

def simple_warning():
	print_status('Simple warning')
	print_warning()

def simple_require_program():
	require_programs(['gcc'])

def simple_require_program_failure():
	require_programs(['no_such_program'])

def simple_require_not_root():
	require_not_root()

def simple_require_root_failure():
	require_root()

