#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from lib_raise_csharp import *

def clean():
	"""Removes any files and directories generated when building."""
	remove_binaries('lib_math_helper')
	remove_binaries('main')

def _configure():
	csc = csharp_get_default_compiler()
	csc.debug = True
	csc.optimize = True
	csc.warnings_all = True
	csc.warnings_as_errors = True
	csharp_save_compiler(csc)

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the library
	csharp_build_shared_library('lib_math_helper.dll', ['math_helper.cs'])

	# Build the program
	csharp_build_program('main.exe', ['main.cs'], ['-r:lib_math_helper.dll'])

	# Run the program
	run_say('./main.exe')





