#!/usr/bin/env python
# -*- coding: UTF-8 -*-

require_module('C#')

def clean():
	"""Removes any files and directories generated when building."""
	rmfile_f('main.exe.mdb')
	rmfile_f('main.exe')

def _configure():
	csc = csharp_get_default_compiler()
	csc.debug = True
	csc.optimize = True
	csc.warnings_all = True
	csc.warnings_as_errors = True
	csharp_save_compiler(csc)

def test():
	"""Builds the program, and runs it."""
	# Setup
	require_not_root()
	clean()
	_configure()

	# Build the program
	sources = ['main.cs', 'math_helper.cs']
	csharp_build_program('main.exe', sources)

	# Run the program
	run_say('./main.exe')





