#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
from lib_raise_java import *

def clean():
	"""Removes any files and directories generated when building."""
	remove_binaries('lib_math')
	remove_binaries('main')

def _configure():
	javac = java_get_default_compiler()
	javac.debug = True
	javac.warnings = True
	javac.verbose = False
	javac.deprecation = False
	java_save_compiler(javac)

def setup_failure():
	# Empty the path and reset the Java module so it finds no compilers
	os.environ['PATH'] = ''
	Java.is_setup = False
	Java.java_compilers = {}
	Java.java_runtimes = {}
	Java.java_jars = {}
	Java.javac = None
	Java.jar = None
	Java.runtime = None
	Java.call_setup()

def build_program():
	clean()
	_configure()

	java_build_program('main.class', ['main.java', 'lib_math.java'])

	java_run_say('main')

def build_jar():
	clean()
	_configure()

	java_build_jar('lib_math.jar', ['lib_math.java'])
	java_build_program('main.class', ['main.java'], ['-cp lib_math.jar'])

	java_run_say('main')

