#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_terminal as Print
import lib_raise_find as Find
import lib_raise_os as OS
import lib_raise_java as Java
import lib_raise_fs as FS

def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('lib_math')
	FS.remove_binaries('main')

def _configure():
	javac = Java.get_default_compiler()
	javac.debug = True
	javac.warnings = True
	javac.verbose = False
	javac.deprecation = False
	Java.save_compiler(javac)

def setup_failure():
	# Empty the path and reset the Java module so it finds no compilers
	os.environ['PATH'] = ''
	Java.is_setup = False
	Java.java_compilers = {}
	Java.java_runtimes = {}
	Java.java_jars = {}
	Java.javac = None
	Java.jar = None
	Java.runtime = None
	Java.setup()

def build_program():
	clean()
	_configure()

	Java.build_program('main.class', ['main.java', 'lib_math.java'])

	Java.run_print('main')

def build_jar():
	clean()
	_configure()

	Java.build_jar('lib_math.jar', ['lib_math.java'])
	Java.build_program('main.class', ['main.java'], ['-cp lib_math.jar'])

	Java.run_print('main')

# Tests that require root
def install_and_uninstall_program():
	# Configure
	OS.require_root()
	clean()
	_configure()

	# Build as a normal user
	def actual_build():
		Java.build_program('main.class', ['main.java', 'lib_math.java'])
	OS.do_as_normal_user(actual_build)

	# Install
	Java.uninstall_program('main.class', 'raise_example')
	Java.install_program('main.class', 'raise_example')

	# Run
	Java.run_print('main')

	# Remove
	Java.uninstall_program('main.class', 'raise_example')

def install_and_uninstall_jar():
	# Configure
	OS.require_root()
	clean()
	_configure()

	# Build as a normal user
	def actual_build():
		Java.build_jar('lib_math.jar', ['lib_math.java'])
		Java.build_program('main.class', ['main.java'], ['-cp lib_math.jar'])
	OS.do_as_normal_user(actual_build)

	# Install
	Java.uninstall_program('main.class', 'raise_example')
	Java.uninstall_jar('lib_math.jar', 'raise_example')
	Java.install_program('main.class', 'raise_example')
	Java.install_jar('lib_math.jar', 'raise_example')

	# Run
	Java.run_print('main')

	# Remove
	Java.uninstall_program('main.class', 'raise_example')
	Java.uninstall_jar('lib_math.jar', 'raise_example')


