#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import lib_raise_terminal as Print
import lib_raise_libraries as Libraries
import lib_raise_os as OS
import lib_raise_java as Java
import lib_raise_fs as FS

def clean():
	"""Removes any files and directories generated when building."""
	FS.remove_binaries('lib_math')
	FS.remove_binaries('main')

def _configure():
	javac = Java.java_get_default_compiler()
	javac.debug = True
	javac.warnings = True
	javac.verbose = False
	javac.deprecation = False
	Java.java_save_compiler(javac)

def setup_failure():
	# Empty the path and reset the Java module so it finds no compilers
	os.environ['PATH'] = ''
	Java.is_setup = False
	Java.java_compilers = {}
	Java.java_runtimes = {}
	Java.java_jars = {}
	Java.javac = None
	Java.jar = None
	Java.runtime = None
	Java.setup()

def build_program():
	clean()
	_configure()

	Java.java_build_program('main.class', ['main.java', 'lib_math.java'])

	Java.java_run_say('main')

def build_jar():
	clean()
	_configure()

	Java.java_build_jar('lib_math.jar', ['lib_math.java'])
	Java.java_build_program('main.class', ['main.java'], ['-cp lib_math.jar'])

	Java.java_run_say('main')

