#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import_module('C')
import_module('Linker')
import_module('AR')

def clean():
	"""Removes any files and directories generated when building."""
	pass

def _configure():
	cc = c_get_default_compiler()
	cc.debug = True
	cc.optimize = True
	cc.warnings_all = True
	cc.warnings_as_errors = True
	c_save_compiler(cc)

	linker = linker_get_default_linker()
	linker_save_linker(linker)

def find_installed_library():
	clean()
	_configure()

	require_shared_library('libSDL', lambda ver: ver >= (1, 2))

def find_missing_library():
	clean()
	_configure()

	require_shared_library('libDoesNotExist')

def find_installed_library_bad_version():
	clean()
	_configure()

	require_shared_library('libSDL', lambda ver: ver >= (99))

