#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import lib_raise_terminal as Print
import lib_raise_libraries as Libraries
import lib_raise_os as OS
import lib_raise_linker as Linker
import lib_raise_ar as AR
import lib_raise_c as C
import lib_raise_fs as FS


def clean():
	"""Removes any files and directories generated when building."""
	pass

def _configure():
	cc = C.get_default_compiler()
	cc.debug = True
	cc.optimize = True
	cc.warnings_all = True
	cc.warnings_as_errors = True
	C.save_compiler(cc)

	linker = Linker.get_default_linker()
	Linker.save_linker(linker)

def find_installed_library():
	clean()
	_configure()

	Libraries.require_shared_library('libSDL', lambda ver: ver >= (1, 2))

def find_missing_library():
	clean()
	_configure()

	Libraries.require_shared_library('libDoesNotExist')

def find_installed_library_bad_version():
	clean()
	_configure()

	Libraries.require_shared_library('libSDL', lambda ver: ver >= (99, 0))

